package com.jeremieguillot.butterfly.domain.model

enum class HabitatType(override val displayName: String) : Displayable {
    PRAIRIES_MARÉCAGEUSES("Prairies marécageuses"),
    PRAIRIES_DE_FAUCHE("Prairies de fauche"),
    MILIEUX_ROCAILLEUX("Milieux rocailleux"),
    CÔTEAUX_BIEN_EXPOSÉS("Côteaux bien exposés"),
    MILIEUX_ANTHROPISÉS("Milieux anthropisés"),
    BAS_MARAIS("Bas marais"),
    CHAMPS_CULTIVÉS("Champs cultivés"),
    CHÊNAIES_CLAIRES("Chênaies claires"),
    EBOULIS("Eboulis"),
    PRAIRIES_MAIGRES("Prairies maigres"),
    MAQUIS("Maquis"),
    FOURRÉS_ROCHEUX("Fourrés rocheux"),
    MILIEUX_MONTAGNARDS("Milieux montagnards"),
    MÉGAPHORBIAIES("Mégaphorbiaies"),
    CHEMINS_FORESTIERS("Chemins forestiers"),
    BORDS_DE_CHEMINS("Bords de chemins"),
    BOIS_CLAIRS("Bois clairs"),
    MILIEUX_OUVERTS_VARIÉS("Milieux ouverts variés"),
    PRAIRIES_BOCAGÈRES("Prairies bocagères"),
    CLAIRIÈRES("Clairières"),
    HAIES("Haies"),
    PRAIRIES_MÉSOPHILES("Prairies mésophiles"),
    FRICHES("Friches"),
    LISIÈRES_CHAUDES("Lisières chaudes"),
    PARCS("Parcs"),
    JARDINS("Jardins"),
    PELOUSES_SÈCHES("Pelouses sèches"),
    LANDES("Landes"),
    TALUS("Talus"),
    BROUSSAILLES("Broussailles"),
    LISIÈRES("Lisières"),
    PRAIRIES_HUMIDES("Prairies humides"),
    FOSSÉS_HUMIDES("Fossés humides"),
    PELOUSES_CALCAIRES("Pelouses calcaires"),
    FRUTICÉES("Fruticées"),
    PRAIRIES_INONDABLES("Prairies inondables"),
    PELOUSES_ARBORÉES("Pelouses arborées"),
    RIPISYLVES("Ripisylves"),
    TOURBIÈRES("Tourbières"),
    FORÊTS_ALLUVIALES("Forêts alluviales"),
    FORÊTS_DE_FEUILLUS("Forêts de feuillus"),
    DUNES("Dunes"),
    GARRIGUE("Garrigue"),
    MARAIS("Marais"),
    JACHÈRES("Jachères"),
    PIEDS_DE_FALAISE("Pieds de falaise"),
    ANCIENNES_CARRIÈRES("Anciennes carrières"),
    LANDES_HUMIDES("Landes humides"),
    CLAIRIÈRES_HUMIDES("Clairières humides")
}
